# Generated by Django 3.1.4 on 2020-12-27 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_subscribe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='subscribe',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
