# Generated by Django 3.1.4 on 2020-12-26 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0004_auto_20201226_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.ForeignKey(default='anonumus', on_delete=django.db.models.deletion.CASCADE, related_name='new_comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
