# Generated by Django 3.1.4 on 2020-12-26 10:20

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20201226_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(default='anonumus', max_length=30, verbose_name=users.models.CustomUser),
        ),
    ]
