# Generated by Django 3.1.4 on 2020-12-28 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20201228_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='moderators',
        ),
        migrations.RemoveField(
            model_name='post',
            name='readers',
        ),
    ]
